services:
  device-app:
    build:
      context: ..
      dockerfile: device/Dockerfile
    image: vigeng/conti/device-app:latest
    container_name: device-app
    environment:
      - MQTT_BROKER_HOST=${MQTT_BROKER_HOST:-192.168.0.112}
      - MQTT_BROKER_PORT=${MQTT_BROKER_PORT:-1883}
    healthcheck:
      test: ["CMD", "python3", "/app/shared/health_check.py"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 15s
    restart: unless-stopped
    network_mode: host
